In [1]:
import pandas as pd 
import numpy  as np 
import re

In [2]:
data = pd.read_csv(r"BL-Flickr-Images-Book.csv")
data.head

<bound method NDFrame.head of       Identifier             Edition Statement      Place of Publication  \
0            206                           NaN                    London
1            216                           NaN  London; Virtue & Yorston
2            218                           NaN                    London
3            472                           NaN                    London
4            480  A new edition, revised, etc.                    London
...          ...                           ...                       ...
8282     4158088                           NaN                    London
8283     4158128                           NaN                     Derby
8284     4159563                           NaN                    London
8285     4159587                           NaN       Newcastle upon Tyne
8286     4160339                           NaN                    London

     Date of Publication                Publisher  \
0            1879 [1878]         S. Tinsley & Co.
1                   1868             Virtue & Co.
2                   1869    Bradbury, Evans & Co.
3                   1851            James Darling
4                   1857     Wertheim & Macintosh
...                  ...                      ...
8282                1838                      NaN
8283            1831, 32          M. Mozley & Son
8284           [1806]-22  T. Cadell and W. Davies
8285                1834         Mackenzie & Dent
8286             1834-43                      NaN

                                                  Title  \
0                     Walter Forbes. [A novel.] By A. A
1     All for Greed. [A novel. The dedication signed...
2     Love the Avenger. By the author of â€œAll for Gr...
3     Welsh Sketches, chiefly ecclesiastical, to the...
4     [The World in which I live, and my place in it...
...                                                 ...
8282  The Parochial History of Cornwall, founded on,...
8283  The History and Gazetteer of the County of Der...
8284  Magna Britannia; being a concise topographical...
8285  An historical, topographical and descriptive v...
8286  Collectanea Topographica et Genealogica. [Firs...

                                                 Author  \
0                                                 A. A.
1                                             A., A. A.
2                                             A., A. A.
3                                             A., E. S.
4                                             A., E. S.
...                                                 ...
8282                 GIDDY, afterwards GILBERT, Davies.
8283                         GLOVER, Stephen - of Derby
8284  LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...
8285                              Mackenzie, E. (Eneas)
8286                                                NaN

                                           Contributors  Corporate Author  \
0                                       FORBES, Walter.               NaN
1          BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
2          BLAZE DE BURY, Marie Pauline Rose - Baroness               NaN
3                           Appleyard, Ernest Silvanus.               NaN
4                                   BROOME, John Henry.               NaN
...                                                 ...               ...
8282  BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...               NaN
8283                                     NOBLE, Thomas.               NaN
8284           GREGSON, Matthew.|LYSONS, Samuel - F.R.S               NaN
8285                               ROSS, M. - of Durham               NaN
8286            BANDINEL, Bulkeley.|Nichols, John Gough               NaN

      Corporate Contributors Former owner  Engraver Issuance type  \
0                        NaN          NaN       NaN   monographic
1                        NaN          NaN       NaN   monographic
2                        NaN          NaN       NaN   monographic
3                        NaN          NaN       NaN   monographic
4                        NaN          NaN       NaN   monographic
...                      ...          ...       ...           ...
8282                     NaN          NaN       NaN   monographic
8283                     NaN          NaN       NaN   monographic
8284                     NaN          NaN       NaN   monographic
8285                     NaN          NaN       NaN   monographic
8286                     NaN          NaN       NaN    continuing

                                             Flickr URL  \
0     http://www.flickr.com/photos/britishlibrary/ta...
1     http://www.flickr.com/photos/britishlibrary/ta...
2     http://www.flickr.com/photos/britishlibrary/ta...
3     http://www.flickr.com/photos/britishlibrary/ta...
4     http://www.flickr.com/photos/britishlibrary/ta...
...                                                 ...
8282  http://www.flickr.com/photos/britishlibrary/ta...
8283  http://www.flickr.com/photos/britishlibrary/ta...
8284  http://www.flickr.com/photos/britishlibrary/ta...
8285  http://www.flickr.com/photos/britishlibrary/ta...
8286  http://www.flickr.com/photos/britishlibrary/ta...

                                             Shelfmarks
0                     British Library HMNTS 12641.b.30.
1                     British Library HMNTS 12626.cc.2.
2                     British Library HMNTS 12625.dd.1.
3                   British Library HMNTS 10369.bbb.15.
4                      British Library HMNTS 9007.d.28.
...                                                 ...
8282  British Library HMNTS|British Library HMNTS 10...
8283  British Library HMNTS|British Library HMNTS 10...
8284  British Library HMNTS|British Library HMNTS 19...
8285  British Library HMNTS|British Library HMNTS 10...
8286  British Library HMNTS|British Library HMNTS 79...

[8287 rows x 15 columns]>

In [3]:
data.columns

Index(['Identifier', 'Edition Statement', 'Place of Publication',
       'Date of Publication', 'Publisher', 'Title', 'Author', 'Contributors',
       'Corporate Author', 'Corporate Contributors', 'Former owner',
       'Engraver', 'Issuance type', 'Flickr URL', 'Shelfmarks'],
      dtype='object')

In [4]:
to_drop = ['Former owner', 'Edition Statement', 'Engraver', 'Issuance type', 'Corporate Author', 'Corporate Contributors', 'Shelfmarks']
data1 = data.copy()

In [5]:
data1 = data1.drop(columns=to_drop)
data1

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...,...
8282,4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...
8283,4158128,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...
8284,4159563,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...
8285,4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...
8286,4160339,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...

In [6]:
data2 = data1.set_index('Identifier')
data2

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
Identifier,,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...
4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...
4158128,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...
4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...

In [7]:
newColumn = data2['Date of Publication'].str.extract(r'^(\d{4})', expand=False)
newColumn

Identifier
206        1879
216        1868
218        1869
472        1851
480        1857
           ...
4158088    1838
4158128    1831
4159563     NaN
4159587    1834
4160339    1834
Name: Date of Publication, Length: 8287, dtype: object

In [8]:
data2['Date of Publication'] = pd.to_numeric(newColumn)
data2

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
Identifier,,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...
4158088,London,1838.0,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...
4158128,Derby,1831.0,M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,NaN,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...
4159587,Newcastle upon Tyne,1834.0,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834.0,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...

In [9]:
place = data2['Place of Publication']
london = place.str.contains('London')
london

Identifier
206         True
216         True
218         True
472         True
480         True
           ...
4158088     True
4158128    False
4159563     True
4159587    False
4160339     True
Name: Place of Publication, Length: 8287, dtype: bool

In [10]:
oxford = place.str.contains("Oxford")

In [11]:
data2['Place of Publication'] = np.where(london, 'London',
                                      np.where(oxford, 'Oxford',
                                               place.str.replace('-', ' ')))

In [12]:
unwanted_characters = ['[', ',', '-',']']
def clean_dates(item):
    dop = item.get('Date of Publication')  # Safe way to access column data
    if pd.isna(dop):  # Handle actual NaN
        return np.NaN
    
    dop = str(dop)
    if dop.startswith('['):  # Check for unwanted start
        dop = dop[1:]
    
    for character in unwanted_characters:
        dop = dop.split(character)[0]  # Split on the character and take the first part
    
    return dop.strip()  # Clean trailing spaces

# Apply function to the DataFrame
data2['Date of Publication'] = data2.apply(clean_dates, axis=1)
data2

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
Identifier,,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...
4158088,London,1838.0,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...
4158128,Derby,1831.0,M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,NaN,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...
4159587,Newcastle upon Tyne,1834.0,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834.0,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...

In [13]:


def clean_author_names(author):
    # Handle missing values
    if pd.isna(author):
        return 'NaN'
    
    # Convert to string
    author = str(author).strip()
    
    # Handle 'nan' as a string
    if author.lower() == 'nan':
        return 'NaN'
    
    # Split by comma
    parts = author.split(',')
    
    # If no comma, assume it's a single name
    if len(parts) == 1:
        name = parts[0]
        # Remove special characters but preserve spaces and hyphens
        name = re.sub(r'[^a-zA-Z\s-]', '', name)
        return name.strip()
    
    # Extract last name and first name
    last_name, first_name = parts[0].strip(), parts[1].strip()
    
    # Clean first name
    # Remove anything after a hyphen (optional, depending on your needs)
    if '-' in first_name:
        first_name = first_name[:first_name.find('-')]
    
    # Remove trailing periods or special characters
    first_name = re.sub(r'[\.\|]+$', '', first_name)
    
    # Capitalize last name
    last_name = last_name.capitalize()
    
    # Combine and return
    return f'{first_name.strip()} {last_name.strip()}'

# Apply the function to the DataFrame
data2['Author'] = data2['Author'].apply(clean_author_names)
data2

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
Identifier,,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A A,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,A. A A.,"BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of â€œAll for Gr...,A. A A.,"BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...",E. S A.,"Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...",E. S A.,"BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...
4158088,London,1838.0,NaN,"The Parochial History of Cornwall, founded on,...",afterwards GILBERT Giddy,"BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...
4158128,Derby,1831.0,M. Mozley & Son,The History and Gazetteer of the County of Der...,Stephen Glover,"NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,NaN,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,Daniel Lysons,"GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...
4159587,Newcastle upon Tyne,1834.0,Mackenzie & Dent,"An historical, topographical and descriptive v...",E. (Eneas) Mackenzie,"ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834.0,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...

In [14]:
def clean_title(title):
    # Handle missing values
    if pd.isna(title):
        return 'NaN'
    
    # Convert to string
    title = str(title).strip()
    
    # Handle 'nan' as a string
    if title.lower() == 'nan':
        return 'NaN'
    
    # Remove content inside brackets
    if title.startswith('['):
        title = title[1:title.find(']')]
    
    # Remove everything after 'by' or 'By' (case-insensitive)
    by_index = title.lower().find('by')
    if by_index != -1:
        title = title[:by_index].strip()
    
    # Remove additional bracketed content
    bracket_index = title.find('[')
    if bracket_index != -1:
        title = title[:bracket_index].strip()
    
    # Remove trailing special characters (optional)
    title = title.strip('.,!?;:- ')
    
    # Capitalize words (using title() for better formatting)
    title = title.title()
    
    return title

# Apply the function to the DataFrame
data2['Title'] = data2['Title'].apply(clean_title)
data2.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
Identifier,,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes,A A,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All For Greed,A. A A.,"BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love The Avenger,A. A A.,"BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, Chiefly Ecclesiastical, To The...",E. S A.,"Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"The World In Which I Live, And My Place In It",E. S A.,"BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...

In [15]:
# Define a dictionary of replacements
place_mapping = {
    r'(?i)london': 'London',  # (?i) makes the regex case-insensitive
    r'(?i)oxford': 'Oxford',
    r'(?i)newcastle upon tyne': 'Newcastle-upon-Tyne'
}

# Use replace() with regex=True
data2['Place of Publication'] = data2['Place of Publication'].replace(place_mapping, regex=True)
data2

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
Identifier,,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes,A A,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All For Greed,A. A A.,"BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love The Avenger,A. A A.,"BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, Chiefly Ecclesiastical, To The...",E. S A.,"Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"The World In Which I Live, And My Place In It",E. S A.,"BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...
4158088,London,1838.0,NaN,"The Parochial History Of Cornwall, Founded On",afterwards GILBERT Giddy,"BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...
4158128,Derby,1831.0,M. Mozley & Son,The History And Gazetteer Of The County Of Der,Stephen Glover,"NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...
4159563,London,NaN,T. Cadell and W. Davies,Magna Britannia; Being A Concise Topographical...,Daniel Lysons,"GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...
4159587,Newcastle-upon-Tyne,1834.0,Mackenzie & Dent,"An Historical, Topographical And Descriptive V...",E. (Eneas) Mackenzie,"ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...
4160339,London,1834.0,NaN,Collectanea Topographica Et Genealogica,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...

In [18]:
data2.to_csv("Final output.csv" ,index=False)